version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: EventLink_db
      POSTGRES_USER: marek
      POSTGRES_PASSWORD: marek
    ports:
      - "5432:5432"
    networks:
      - eventlink_net

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: marek_access
      MINIO_ROOT_PASSWORD: marek_secret
    volumes:
      - ./minio_data:/data
    networks:
      - eventlink_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventlink_backend
    depends_on:
      - db
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/EventLink_db
      SPRING_DATASOURCE_USERNAME: marek
      SPRING_DATASOURCE_PASSWORD: marek
      MINIO_URL: http://minio:9000
    ports:
      - "8080:8080"
    networks:
      - eventlink_net

networks:
  eventlink_net:
